### ISSUE TITLE
Unable to overwrite default key binding

### ISSUE THREAD

**Issue by Naahuel** [joelpt/sublimetext-automatic-backups#10]
I'm running Sublime Text 2.0.2 on Windows 7 x64.

I've setup custom user key bindings to jump forward and back in the backup history, like so:

`{ "keys": ["ctrl+shift+y"], "command": "automatic_backups", "args": { "command": "step", "forward": true }},
{ "keys": ["ctrl+shift+z"], "command": "automatic_backups", "args": { "command": "step", "forward": false }},`

The problem is that the default keybind (`["ctrl+alt+]"]`) still works and it overrides my `\` key (for some reason) and the only way around is to edit the Default keymap and remove those binds. The problem is that this file gets overwritten with every update.

Thank you!

**Comment by joelpt** [comment]
I believe you can avoid this problem by editing the "Settings - User" files, rather than the "Settings - Default" files.
