### ISSUE TITLE
Backup save error

### ISSUE THREAD

**Issue by cupcakegunter** [joelpt/sublimetext-automatic-backups#11]
I am running sublime 3 Beta and I can't tell if this is a beta issue, plugin issue or settings issue.

I get an error "TypeError: unorderable types: int() > NoneType()" when I save a file and it tries to back it up.

**Comment by joelpt** [comment]
It's now updated for ST3. Should show up in Package Control in a few days.

cupcakegunter's reported issue was definitely caused by the migration of ST3 to Python 3; the plugin is now compatible with (only) ST3/Python3.

**Comment by asakasinsky** [comment]
Thank you!!!
