### ISSUE TITLE
Sublime text 3 ?

### ISSUE THREAD

**Issue by tsi** [joelpt/sublimetext-automatic-backups#13]
I love this plugin, but now we're using ST3 I really miss it, will you release an ST3 version? can it be used today with ST3?

**Comment by tsi** [comment]
Any plans for a ST3 version? any alternatives?

**Comment by margaritis** [comment]
ST3 support would be really nice!

**Comment by joelpt** [comment]
ST3 support is now implemented. Should show up in Package Control in a few days.
